layout_spectrum: 1
color:
  saturation: 0.4693966
  lightness: 1
  brandStrength: 0.4767025
  brandColors:
    - '#D8C5C1'
    - '#2B2144'
    - '#F1F2F6'
    - '#585872'
    - '#827684'
  rhythmicContrast: 0.03506747
typography_spectrum: 0.546595
name: CompaBrew
